# Site settings
title: Vector
email: vector-users@googlegroups.com
description: An on-host performance monitoring framework which exposes hand picked high resolution metrics to every engineer’s browser
baseurl: ""
url: "http://vectoross.io"
twitter_username: vectoross
github_username:  Neflix

# Build settings
markdown: kramdown
