# Site settings
title: Vector
email: vector-users@googlegroups.com
description: An on-host performance monitoring framework which exposes hand picked high resolution metrics to every engineer’s browser
baseurl: ""
url: "http://vectoross.io"
twitter_username: vectoross
github_username:  Neflix

collections:
  docs:
    output: true

defaults:
  - scope:
      path: ""
      type: docs
    values:
      layout: docs

# Build settings
markdown: kramdown
