# Site settings
title: Vector
email: vector-users@googlegroups.com
description: An on-host performance monitoring framework which exposes hand picked high resolution metrics to every engineer’s browser
baseurl: ""
url: "http://getvector.io"
twitter_username: vectoross
github_username:  Neflix
bintray_binary: https://github.com/Netflix/vector/releases/download/v2.0.0-beta.1/vector.tar.gz

collections:
  docs:
    output: true

defaults:
  - scope:
      path: ""
      type: docs
    values:
      layout: docs

# Build settings
markdown: kramdown
